### ISSUE TITLE
Why install under "dependencies"?

### ISSUE THREAD

**Issue by JoshMcCullough** [nfour/types-installer#5]
>Types are by default saved to dependencies or devDependencies, wherever the dependency exists.

What is the benefit of ever installing types as deps instead of dev-deps? Aren't they always going to be dev-time-only?

**Comment by nfour** [comment]
Some types are necessary to be used by dependents. For example, if you export a value wrapped in a Bluebird promise, you need to also have the `@types/bluebird` in your `dependencies` for things to work.

**Comment by piglovesyou** [comment]
@JoshMcCullough I think so. Types for dev-deps are only necessary on development and should not be installed on production.

**Comment by piglovesyou** [comment]
@nfour Wow, I think this should be improved, isn't it?

**Comment by nfour** [comment]
@piglovesyou there is a CLI option to force install for dev deps, `-D`, and by default it will install to the same location where the dependency is. This is the correct behaviour.

**Comment by JoshMcCullough** [comment]
@nfour -- to be clear, types should always be installed as `--save-dev`, as dev dependencies. Types do not provide actual executable code, but only describe the types of the library to which they relate. That's all I was saying.

**Comment by nfour** [comment]
@JoshMcCullough maybe I am mistaken, but the way I understood it is that when your own library with `{ declarations: true }` outputs its declarations, it requires that they be available from the npm library in the form as a dependency.

Is there some docs that define best practice here?

**Comment by JoshMcCullough** [comment]
You're correct that if you are publishing a library, you include types as deps rather than dev-deps. It depends on the end user who is using your types-installer package. The way you have it now, IIRC, is that types are installed as deps rather than dev-deps by default, but we can override this with the `--toDev` argument. 

In hindsight, I think this is okay. If my project is _not_ a library, I want types installed as dev-deps and will use said argument to accomplish that. If my project _is_ a library which is being re-packaged and released, types should get installed as regular deps so that consumers will have all the relevant types when they install my package. 

I'll close this since I opened it. :+1:
