### ISSUE TITLE
Issue with resolving '@' prefixed dependnecies

### ISSUE THREAD

**Issue by mannol** [nfour/types-installer#6]
## Summary
Despite the title of this issue, there could be 2 reasons the issue occurs:
1. The dependency has `@` symbol in its name.
2. The dependency has a path in its name.

## Steps to reproduce
```sh
$ yarn install @nestjs/common
$ types-installer install --selection dependencies --toDev
```

The installation will fail because this is the output in `package.json`:
```json
"devDependencies": {
    "@types/": "nestjs/common"
}
```

**Comment by nfour** [comment]
PR welcome!

**Comment by nfour** [comment]
Just fixed this. Should resolve: `@storybook/addons` to `@types/storybook__addons`
